version: "3.8"
services:
#torrent
  Aria2-Pro:
    container_name: aria2c
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=RPC_PLACEHOLDER
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Europe/Spain
    volumes:
      - ${PWD}/aria2-config:/config
      - ${PWD}/aria2-downloads:/downloads
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

# Torrents Web UI
  AriaNg:
    container_name: ariaui
    image: p3terx/ariang
    command: --port 6880 --ipv6
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
#Video Server
  plex:
    container_name: jay_plex
    image: jaymoulin/plex
    expose:
      - 32400
      - 33400
    environment:
      - TZ=Europe/Spain
    volumes:
      - ${PWD}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${PWD}/aria2-downloads/Media:/media
      - ${PWD}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host"
#File manager: https://docs.technotim.live/posts/meet-file-browser/
  file-browser:
    image: filebrowser/filebrowser
    container_name: fileb
    #user: id -u user:id -g user
    user: 1000:1000
    ports:
      - 8081:80
    volumes:
      - ${PWD}/aria2-downloads:/srv
      - ${PWD}/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true