version: "3.8"
services:
  #torrent
  Aria2-Pro:
    container_name: aria2c
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=${PW}
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=${TZ}
    volumes:
      - ${ARIA2}:/config
      - ${DOWNLOADS}:/downloads
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
# Torrents Web UI
  AriaNg:
    container_name: ariaui
    image: p3terx/ariang
    command: --port 6880 --ipv6
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
#Video Server
  plex:
    container_name: plex
    image: jaymoulin/plex
    expose:
      - 32400
      - 33400
    environment:
      - TZ=${TZ}
    volumes:
      - ${PLEX}/plex_config/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${GENERAL_MEDIA}:/media
      - ${PLEX}/plex_config/tmp:/tmp
    restart: unless-stopped
    network_mode: "host"
#File manager:
  file-browser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    #user: id -u user:id -g user
    user: ${PUID}:${PGID}
    ports:
      - 8081:80
    volumes:
      - ${MEDIA_DIRECTORY}:/srv
      - ${FILEBROWSER}/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  #################
  sonarr:
    ## Rasbian32 -> image: mdhiggins/sonarr-sma:latest-armhf
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    logging:
      driver: json-file
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SONARR}:/config
      - ${GENERAL_MEDIA}:/media
      - ${DOWNLOADS}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  #################
  jackett:
    #Raspbian32 -> image: lscr.io/linuxserver/jackett:0.21.185
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${JACKETT}:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
